#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

import os
import pygame

from time import sleep
from modules.guitar_pastas_de_dados import pasta_raiz
#from modules.quitar_arquivos_alvo import target_character_img

pygame.init() 
white = (255, 255, 255)
width, height = 400, 600
target_character_img = pasta_raiz + target_character_img

display_surface = pygame.display.set_mode((width, height))
pygame.display.set_caption('SiUR Combate')

while True: 
    image = pygame.image.load('.target_character_img')
    display_surface.fill(white) 
    display_surface.blit(image, (50, 50))
    for event in pygame.event.get() : 
        if event.type == pygame.QUIT : 
            pygame.quit() 
            exit()
    pygame.display.update()
    sleep(0.5)